<?php

namespace AppBundle\Repository;

/**
 * choixRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class choixRepository extends \Doctrine\ORM\EntityRepository
{
}
