<?php

namespace AppBundle\Repository;

/**
 * fondRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class fondRepository extends \Doctrine\ORM\EntityRepository
{
}
