<?php

namespace AppBundle\Repository;

/**
 * piece_jointeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class piece_jointeRepository extends \Doctrine\ORM\EntityRepository
{
}
