<?php

namespace AppBundle\Repository;

/**
 * reunionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reunionRepository extends \Doctrine\ORM\EntityRepository
{
}
