<?php

namespace AppBundle\Repository;

/**
 * versementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class versementRepository extends \Doctrine\ORM\EntityRepository
{
}
